Removed unnecessary comments
rahuldkjain/github-profile-readme-generator pull request #105
Opened 2020-09-10 12:12 UTC by esdraspavon

Hi! I have removed unnecessary comments.

2020-09-13 12:45 UTC, rahuldkjain requested changes
Please fix the comment

2020-09-13 12:45 UTC, rahuldkjain commented on src/pages/index.js
> -	// keep cache updated
Don't remove this comment

2020-09-13 13:50 UTC, chetan2088 approved these changes

2020-10-20 14:01 UTC, harshcut commented
Closing the Pull Request due to inactivity.
Is this a mistake? Open a new Pull Request linking this PR for reference.

2020-10-20 14:01 UTC, closed without merging