Added Resume field in the work section
rahuldkjain/github-profile-readme-generator pull request #214
Opened 2020-10-03 05:25 UTC by nidhi-bhanushali

Added Resume field between blog and funfact.

2020-10-03 05:32 UTC, rahuldkjain requested changes
Please integrate the resume field in `src/components/markdown.js` and `src/components/markdownPreview.js`

2020-10-03 05:37 UTC, nidhi-bhanushali commented
On it!

2020-10-03 11:01 UTC, nidhi-bhanushali commented
Hey , @rahuldkjain , I've made the changes , so are they approved?
You haven't closed the issue yet , so

2020-10-04 05:33 UTC, rahuldkjain requested changes
Please fix the respective comments.

2020-10-04 05:33 UTC, rahuldkjain commented on package.json
> +    "netlify-cli": "^2.64.1",
please remove `netlify-cli` from `package.json`.

2020-10-04 05:33 UTC, rahuldkjain commented on package.json
> +    "gatsby-plugin-sharp": "^2.6.38",
Please don't change the version.

2020-10-04 05:33 UTC, rahuldkjain commented on .netlify/state.json
> +{
remove this file

2020-10-04 05:33 UTC, rahuldkjain commented on package.json
> +    "gatsby-plugin-sharp": "^2.6.38",
Please don't change the version.

2020-10-04 05:33 UTC, rahuldkjain commented on package.json
> +    "netlify-cli": "^2.64.1",
remove `netlify-cli` from `package.json`

2020-10-04 06:52 UTC, rahuldkjain commented
@nidhi-bhanushali delete `package-lock.json` file too from this PR.

2020-10-04 07:07 UTC, merged