add searchbar
rahuldkjain/github-profile-readme-generator pull request #239
Opened 2020-10-05 20:58 UTC by j23saw

Closes #217 
Added a search bar to make it convenient to search for skills.
Here's a demo:
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/34836779/95131349-85acd380-077b-11eb-96b3-9016f81a8942.gif)
Suggest some changes if needed.

2020-10-06 18:02 UTC, rahuldkjain commented
@j23saw 
Few suggestions:
1. Change the border of `Search Skill` input box with respect to the design style guide. I mean the border and border-radius must be the same as the other buttons.
2. Border Shadow on the Skills categories can be removed. Although we can keep an `hr` tag below the category title.

2020-10-06 19:31 UTC, j23saw commented
@rahuldkjain working on it!

2020-10-07 18:42 UTC, j23saw commented
I have implemented your suggestions, any more changes needed?

2020-10-08 17:09 UTC, rahuldkjain requested changes
Please ignore the changes in `package-lock.json` in this PR. 
Fix the comments.

2020-10-08 17:09 UTC, rahuldkjain commented on package.json
> +    "gatsby-plugin-sharp": "^2.6.38",
remove this change from PR.

2020-10-08 17:09 UTC, rahuldkjain commented on package.json
> +    "develop": "gatsby develop -H 0.0.0.0",
remove this change too

2020-10-11 08:11 UTC, j23saw commented
@rahuldkjain please review the changes.

2020-10-11 08:22 UTC, rahuldkjain commented
Will review soon @j23saw.

2020-10-11 10:01 UTC, rahuldkjain approved these changes
Superb @j23saw. Really liked the user experience of the search bar. Impressed to see that you took care of edge cases like `no results found` too.

2020-10-11 10:02 UTC, merged

2020-10-11 10:10 UTC, j23saw commented
Thank you so much! Really appreciate your feedback✌️