added Issues and Pull Requests link to footer [Issue #263]
rahuldkjain/github-profile-readme-generator pull request #265
Opened 2020-10-11 14:20 UTC by dalmia007

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [✓ ] Feature
- [ ] Bug Fix
- [ ] Enhancement
- [ ] Documentation Update

## Description
Added Issues and Pull Requests link to footer

## Related Tickets & Documents
Issue 263

## QA Instructions, Screenshots, Recordings
Check the footer for links to Issues and Pull Requests page

## Added to documentation?

- [ ] readme

2020-10-11 17:15 UTC, rahuldkjain requested changes
Please remove changes of `package-lock.json` from this PR.

2020-10-11 18:55 UTC, dalmia007 commented
@rahuldkjain  I have tried to do it several times. However, git is still picking up that change in package-lock.json. It is not really a change. The file is still the same. I actually copied it from the master repo just to make sure its okay.

2020-10-14 05:12 UTC, rahuldkjain requested changes
Please fix the comments.

2020-10-14 05:12 UTC, rahuldkjain commented on src/components/footer.js
> +              aria-label="Releases on Github rahuldkjain/github-profile-readme-generator"
change aria-label to `Issues in rahuldkjain/github-profile-readme-generator`

2020-10-14 05:12 UTC, rahuldkjain commented on src/components/footer.js
> +              aria-label="Releases on Github rahuldkjain/github-profile-readme-generator"
change aria-label to `Pull Requests in rahuldkjain/github-profile-readme-generator`

2020-10-14 07:11 UTC, dalmia007 commented
@rahuldkjain the aria labels have been corrected

2020-10-18 03:02 UTC, rahuldkjain approved these changes
Superb @dalmia007.

2020-10-18 03:02 UTC, merged