fix margin in mobile screen
rahuldkjain/github-profile-readme-generator pull request #271
Opened 2020-10-16 04:53 UTC by thauska

## What type of PR is this? (check all applicable)

- [x ] Refactor
- [x] Feature
- [x ] Bug Fix
- [x] Enhancement
- [x] Documentation Update

## Description
fix margin in mbile screen and eslint warning gone with  #248 

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added to documentation?

- [x] readme

2020-10-18 03:10 UTC, rahuldkjain commented
@thauska Could you please unstage changes in all the files which is irrelevant to issue #248?

2020-10-18 03:11 UTC, rahuldkjain requested changes
Please unstage all changes which are not relevant to issue #248.

2020-10-18 03:59 UTC, thauska commented
Ok

2020-10-18 06:32 UTC, thauska commented
it's updated

2020-10-19 19:44 UTC, thauska reviewed
Here is the unstaged changes

2020-10-24 06:16 UTC, rahuldkjain requested changes
@thauska You only need to change the margin in `src/components/work.js` for this issue.

2020-10-24 06:17 UTC, rahuldkjain commented
## Before
<img width="1256" alt="Screenshot 2020-10-24 at 11 44 50 AM" src="https://user-images.githubusercontent.com/26406279/97069517-9324e300-15ee-11eb-80ce-23937c551233.png">

## After
<img width="1256" alt="Screenshot 2020-10-24 at 11 44 42 AM" src="https://user-images.githubusercontent.com/26406279/97069515-9029f280-15ee-11eb-9feb-b625d3debe2f.png">

@thauska Please undo this change too.

2025-10-22 11:15 UTC, closed without merging