test markdown.js
rahuldkjain/github-profile-readme-generator pull request #319
Opened 2020-10-24 18:22 UTC by wandersonpsantos

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Enhancement
- [ ] Documentation Update

## Description
#299 

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added to documentation?

- [ ] readme

2020-10-25 10:22 UTC, Citrinin requested changes
Thanks for your efforts, looks almost good! 
But we shall rely only on one testing library.
Please, rebase to master & get rid of `yarn-lock.json` changes (it does not exist in master)

2020-10-25 10:22 UTC, Citrinin commented on src/components/__tests__/markdown.test.js
> +import renderer from "react-test-renderer"
Please rely on `enzyme-to-json` library and do not use `react-test-renderer`  - there is no trace of it in `master` now. Can see [here](https://github.com/rahuldkjain/github-profile-readme-generator/blob/master/src/components/__tests__/work.test.js#L22)

2020-10-26 14:30 UTC, Citrinin approved these changes
LGTM! 👍 
Thank you for your effort.

2020-10-26 14:31 UTC, rahuldkjain approved these changes
Superb @wandersonpsantos

2020-10-26 14:31 UTC, merged