Add Angular 2+ icon, link
rahuldkjain/github-profile-readme-generator pull request #374
Opened 2021-03-03 12:11 UTC by frntnd93

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Enhancement
- [ ] Documentation Update

## Description
Adds [Angular 2+](https://angular.io/) as a skill under Frontend Development and website link.
## Related Tickets & Documents
Related to #373 
## QA Instructions, Screenshots, Recordings
![image](https://user-images.githubusercontent.com/41643887/109803626-56b76280-7c32-11eb-906b-dc1238c1a6dd.png)

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] readme

2021-03-31 07:14 UTC, aravindvnair99 commented on src/constants/skills.js
> +    "https://raw.githubusercontent.com/devicons/devicon/master/icons/angularjs/angularjs-plain.svg",
```suggestion
    "https://angular.io/assets/images/logos/angular/angular.svg",
```

2021-03-31 07:15 UTC, aravindvnair99 requested changes
@frntnd93 [AngularJS](https://angularjs.org/) logo is different from [Angular](https://angular.io/) logo.

2021-03-31 09:53 UTC, aravindvnair99 approved these changes

2021-03-31 09:55 UTC, frntnd93 commented
> @frntnd93 [AngularJS](https://angularjs.org/) logo is different from [Angular](https://angular.io/) logo.

You're right, commit suggestion applied

2021-05-03 16:18 UTC, harshcut approved these changes
LGTM 👍

2021-05-10 06:38 UTC, merged